### ISSUE TITLE
[BUG] git simply does not

### ISSUE THREAD

**Issue by Jajoo2** [rohankishore/Aura-Text#71]
# Bug
i installed all of the dependencies, but git module isn't found

## Describe the bug
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/jajoo/Aura-Text/main.py", line 9, in <module>
    from auratext.Core.window import Window
  File "/home/jajoo/Aura-Text/auratext/Core/window.py", line 10, in <module>
    import git
ModuleNotFoundError: No module named 'git'
take a wild guess
<br>

## To Reproduce
1. attempt to run the py

## Expected behavior
i expected it to run

## Desktop Specs
 - OS: [Linux Mint MATE]
 - Aura Text Version: [no idea]

**Comment by rohankishore** [comment]
You'll have to install gitpython library
